name: Py Lambda Deploy
author: Mariam Maarouf
description: Deploy python code to AWS Lambda with dependencies in a separate layer.
inputs:
  requirements_txt:
    description: the name/path to the requirements.txt file
    required: true
    default: 'requirements.txt'
  lambda_layer_arn:
    description: The ARN for the Lambda layer the dependencies should be pushed to without the version (every push is a new version).
    required: true
  lambda_function_name:
    description: The Lambda function name. Check the AWS docs/readme for examples.
    required: true
  use_s3:
    description: Whether to use S3 (true) or not (false) for the dependencies layer upload.
    required: false
    default: 'false'
  s3_bucket_name:
    description: The S3 bucket name for the dependencies layer upload.
    required: false
    default: no-bucket-name-here
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.requirements_txt }}
    - ${{ inputs.lambda_layer_arn }}
    - ${{ inputs.lambda_function_name }}
branding:
  icon: 'layers'
  color: 'yellow'
